import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, it } from 'node:test';
import { z } from 'zod';
import { FIELD_TYPES, ISSUES, SECTIONS, formatReference, worldFormatDoc } from '#engine';
import { CLIENT_CTX, GRADER_CTX, HANDLER_CTX, JOB_CTX, SEED_CTX } from '../src/engine/ctx.ts';

const CODE_DIR = path.resolve(import.meta.dirname, '..');
const WORLD_FORMAT = path.resolve(CODE_DIR, '../prod/world-format.md');

function docs(...args: string[]): { status: number | null; stdout: string; stderr: string } {
  const r = spawnSync('node', ['--import', 'tsx', 'src/cli/worldplay.ts', 'docs', ...args], { cwd: CODE_DIR, encoding: 'utf8' });
  return { status: r.status, stdout: r.stdout, stderr: r.stderr };
}

describe('world-format.md', () => {
  it('R16 prod/world-format.md is what `npm run docs` writes', async () => {
    const onDisk = await readFile(WORLD_FORMAT, 'utf8').catch(() => '(missing)');
    assert.equal(onDisk, worldFormatDoc(), 'prod/world-format.md is stale. Run `npm run docs` in code/ and commit prod/world-format.md.');
  });

  it('R14 starts with a generated-file header, then the format reference', () => {
    const doc = worldFormatDoc();
    assert.equal(
      doc.split('\n').slice(0, 3).join('\n'),
      '> Generated by `bun run docs` in code/ from code/src/engine/format.ts. Do not edit by hand.\n\n# World format',
    );
    assert.ok(doc.endsWith(formatReference()));
  });

  it('R14 worldplay docs --out writes the same bytes on every run', async () => {
    const dir = await mkdtemp(path.join(tmpdir(), 'docs-'));
    const out = path.join(dir, 'world-format.md');
    const first = docs('--out', out);
    assert.equal(first.status, 0, first.stderr);
    assert.equal(first.stdout, `wrote ${out}\n`);
    const once = await readFile(out, 'utf8');
    assert.equal(docs('--out', out).status, 0);
    const twice = await readFile(out, 'utf8');
    assert.equal(twice, once);
    assert.equal(once, worldFormatDoc());
  });

  it('R14 docs refuses a positional argument and an unknown option with exit 2', () => {
    const extra = docs('somewhere.md');
    assert.equal(extra.status, 2);
    assert.match(extra.stderr, /^docs takes no positional arguments\n/);
    const flag = docs('--frob');
    assert.equal(flag.status, 2);
    assert.match(flag.stderr, /usage: worldplay <command>/);
  });
});

describe('formatReference coverage', () => {
  const md = formatReference();
  const lines = md.split('\n');

  it('R15 has one heading per section and the WorldEdit apply order', () => {
    for (const s of SECTIONS) assert.equal(lines.filter((l) => l === `## ${s}`).length, 1, s);
    assert.ok(lines.includes('The only way a world changes. Apply order: remove, then upsert, then patch.'));
  });

  it('R15 gives every field type its doc and its example definition', () => {
    for (const t of Object.values(FIELD_TYPES)) {
      assert.ok(md.includes(`### ${t.type}\n\n${t.doc}\n\nExample: \`${JSON.stringify(t.examples.def)}\``), t.type);
    }
    assert.ok(lines.includes('Example: `{"type":"money","currency":"USD","min":0}`'));
    assert.ok(lines.includes('Example: `{"type":"state","states":["open","closed"],"initial":"open","transitions":{"open":["closed"],"closed":[]}}`'));
  });

  it('R15 lists every ctx member sig and doc for every snippet kind', () => {
    const registries = { handler: HANDLER_CTX, job: JOB_CTX, seed: SEED_CTX, grader: GRADER_CTX, client: CLIENT_CTX };
    for (const [kind, registry] of Object.entries(registries)) {
      assert.ok(lines.includes(`### ${kind}`), kind);
      for (const [name, m] of Object.entries(registry)) assert.ok(lines.includes(`ctx.${name}: ${m.sig}. ${m.doc}`), `${kind} ${name}`);
    }
    assert.ok(lines.includes('ctx.fail: (status: 400 | 404 | 409 | 422, code, message, extra?: { type?: string; param?: string }) => never. Abort the call. Nothing is written. The optional extra fills $type and $param in the world error template.'));
  });

  it('R15 lists every issue code once, with severity, owner, expected and hint', () => {
    for (const code of Object.keys(ISSUES)) {
      assert.equal(lines.filter((l) => l.startsWith(`- \`${code}\` (`)).length, 1, code);
    }
    assert.ok(lines.includes('## Issues'));
    assert.ok(lines.includes(
      '- `ref.unknown` (error, owner at_path): expected one of the declared <kind> names. Hint: Known <kind> names: <known names>.',
    ));
    assert.ok(lines.includes(
      '- `action.unexercised` (warning, owner actions): expected every action called by at least one test or solution. Hint: Remove <action>, or call it from a test or a task solution.',
    ));
    assert.ok(lines.includes(
      '- `snippet.call_quota` (error, owner at_path): expected at most 20000 ctx calls per run. Hint: Look for a loop that never ends or lists inside a loop.',
    ));
  });

  it('R15 is identical on every call', () => {
    assert.equal(formatReference(), md);
    assert.equal(worldFormatDoc(), worldFormatDoc());
  });
});

/** A documented shell command: the line's executable part, comments stripped, `\` continuations joined. */
function shCommands(markdown: string): string[] {
  const out: string[] = [];
  for (const block of markdown.matchAll(/```sh\n([\s\S]*?)```/g)) {
    const joined = block[1]!.replace(/\\\n\s*/g, ' ');
    for (const raw of joined.split('\n')) {
      const line = raw.replace(/\s+#.*$/, '').trim();
      if (line !== '' && !line.startsWith('#')) out.push(line);
    }
  }
  return out;
}

const REPO_DIR = path.resolve(CODE_DIR, '..');
const PACKAGE = z.object({ scripts: z.record(z.string(), z.string()) }).parse(JSON.parse(readFileSync(path.join(CODE_DIR, 'package.json'), 'utf8')));
/** Scripts whose job is to run the suite or the build: `--help` would run them, so only their existence is checked. */
const NOT_CLI = new Set(['typecheck', 'test', 'check', 'e2e']);

function helpOf(file: string, ...args: string[]): { status: number | null; stdout: string } {
  const r = spawnSync('node', ['--import', 'tsx', file, ...args, '--help'], { cwd: CODE_DIR, encoding: 'utf8' });
  return { status: r.status, stdout: r.stdout };
}

/** The README and its reference page, research/readme-reference.md, which holds the detail the README links to. */
const readmeDocs = (): string => ['README.md', 'research/readme-reference.md'].map((f) => readFileSync(path.join(REPO_DIR, f), 'utf8')).join('\n');

describe('documented commands exist', () => {
  const docs = { 'README.md': shCommands(readmeDocs()), 'AGENTS.md': shCommands(readFileSync(path.join(REPO_DIR, 'AGENTS.md'), 'utf8')) };

  it('R17 the parser finds the documented commands', () => {
    assert.ok(docs['README.md'].includes('bun run worldplay serve ../prod/worlds/helpdesk --port 4000'));
    assert.ok(docs['AGENTS.md'].includes('bun run docs'));
    assert.ok(docs['AGENTS.md'].includes('bun run worldplay check  ../prod/worlds/helpdesk'));
    assert.ok(docs['README.md'].includes('bun run worldgen "add partial refunds" --world ../prod/worlds/gen-refunds'));
  });

  for (const [file, commands] of Object.entries(docs)) {
    for (const cmd of commands.filter((c) => c.startsWith('bun run ') || c.startsWith('npm run '))) {
      it(`R17 ${file}: \`${cmd.slice(0, 60)}\` names a package.json script and, for CLIs, answers --help with 0`, () => {
        const script = cmd.split(/\s+/)[2]!;
        const body = PACKAGE.scripts[script];
        assert.ok(body !== undefined, `package.json has no script "${script}"`);
        if (NOT_CLI.has(script)) return;
        const m = /^(?:bun|tsx) (\S+\.ts)(?: (\w+))?$/.exec(body);
        if (m === null) return; // e.g. e2e: its own script, checked by existence
        const [, entry, fixed] = m;
        // npm needs `--` before script arguments; bun takes them as is.
        const words = cmd.split(/\s+/).slice(3);
        const first = words[0] === '--' ? words[1] : words[0];
        const sub = fixed ?? (/^[a-z]+$/.test(first ?? '') ? first : undefined);
        const r = helpOf(entry!, ...(sub === undefined ? [] : [sub]));
        assert.equal(r.status, 0, `${script} ${sub ?? ''} --help`);
        if (script === 'worldplay' && sub !== undefined) assert.ok(r.stdout.includes(`\n  ${sub} `), `worldplay usage lists ${sub}`);
      });
    }
  }

  it('R17 worldplay --help lists exactly the subcommands the docs use', () => {
    const r = helpOf('src/cli/worldplay.ts');
    assert.equal(r.status, 0);
    const listed = [...r.stdout.matchAll(/^ {2}([a-z]+) /gm)].map((m) => m[1]);
    assert.deepEqual(listed, ['check', 'serve', 'verify', 'openapi', 'grade', 'docs']);
  });

  it('R17 every other documented script or tsx entry exists and answers --help with 0', () => {
    for (const cmd of [...docs['README.md'], ...docs['AGENTS.md']].filter((c) => c.startsWith('npx tsx '))) {
      const entry = cmd.split(/\s+/)[2]!;
      assert.ok(existsSync(path.join(CODE_DIR, entry)), entry);
      assert.equal(helpOf(entry).status, 0, `${entry} --help`);
    }
    for (const cmd of [...docs['README.md'], ...docs['AGENTS.md']].filter((c) => /^(\.\.\/)?scripts\//.test(c))) {
      const rel = cmd.split(/\s+/)[0]!.replace(/^\.\.\//, '');
      assert.ok(existsSync(path.join(REPO_DIR, rel)), rel);
    }
  });
});

interface DocLine { readonly file: string; readonly line: number; readonly text: string }

/** Every command line in a file's sh blocks with its 1-based line number, `\` continuations joined. */
function shLines(file: string): DocLine[] {
  const out: DocLine[] = [];
  let inSh = false;
  let pending: DocLine | null = null;
  readFileSync(path.join(REPO_DIR, file), 'utf8').split('\n').forEach((raw, i) => {
    if (raw.startsWith('```')) {
      inSh = !inSh && raw.trim() === '```sh';
      return;
    }
    if (!inSh) return;
    const text = raw.replace(/\s+#.*$/, '').trim();
    if (text === '' || text.startsWith('#')) return;
    const joined = pending === null ? text : `${pending.text} ${text}`;
    const start = pending === null ? i + 1 : pending.line;
    pending = joined.endsWith('\\') ? { file, line: start, text: joined.slice(0, -1).trim() } : null;
    if (pending === null) out.push({ file, line: start, text: joined });
  });
  return out;
}

const DOC_FILES = ['README.md', 'research/readme-reference.md', 'AGENTS.md', 'prod/README.md', 'prod/design.md'];

describe('documented worldplay subcommands, worldgen flags and runner', () => {
  const lines = DOC_FILES.flatMap(shLines);
  const subs = [...helpOf('src/cli/worldplay.ts').stdout.matchAll(/^ {2}([a-z]+) /gm)].map((m) => m[1]);
  const flags = [...helpOf('src/cli/worldgen.ts').stdout.matchAll(/^ {2}(-[-a-z]+)/gm)].map((m) => m[1]);
  const unquoted = (t: string): string => t.replace(/"[^"]*"/g, '""');

  it('R17 reads the sub-commands and flags from the CLIs', () => {
    assert.deepEqual(subs, ['check', 'serve', 'verify', 'openapi', 'grade', 'docs']);
    assert.deepEqual(flags, ['--fidelity', '--openapi', '--only', '--csv', '--world', '--out', '--model', '--transport', '--budget-usd', '--max-minutes', '-h']);
  });

  it('R17 finds sh blocks in all four doc files', () => {
    for (const f of DOC_FILES) assert.ok(lines.some((l) => l.file === f), f);
    assert.ok(lines.some((l) => l.file === 'prod/design.md' && /worldplay(?: --)? check/.test(l.text)));
  });

  it('R17 every `worldplay <sub>` is a subcommand; a miss names file:line', () => {
    for (const l of lines) {
      if (l.text.startsWith('docker ')) continue; // `worldplay` there is the image name, checked in the Docker block
      const m = /\bworldplay(?: --)? (\S+)/.exec(unquoted(l.text));
      if (m !== null) assert.ok(subs.includes(m[1]), `${l.file}:${l.line}: worldplay ${m[1]} is not a subcommand`);
    }
  });

  it('R17 every `worldgen --flag` is a flag cli/worldgen.ts parses; a miss names file:line', () => {
    for (const l of lines) {
      if (!/\bworldgen\b/.test(unquoted(l.text))) continue;
      for (const f of unquoted(l.text).match(/(?<=\s)--?[a-z][-a-z]*/g) ?? []) {
        assert.ok(flags.includes(f), `${l.file}:${l.line}: worldgen ${f} is not parsed`);
      }
    }
  });

  it('R17 docs use bun, and npm only for the Node gate; a miss names file:line', () => {
    for (const l of lines) assert.ok(!/\bnpm (?:test|install|run (?!check:node\b))/.test(l.text), `${l.file}:${l.line}: ${l.text}`);
  });

  it('R17 AGENTS.md and design.md do not call shipped work planned', () => {
    for (const f of ['AGENTS.md', 'prod/design.md']) {
      readFileSync(path.join(REPO_DIR, f), 'utf8').split('\n').forEach((t, i) => {
        assert.ok(!/wg-cli-run|wg-run-slice|engine-lints|wg-report|wg-input-openapi|wg-input-csv|wg-input-conformance/.test(t), `${f}:${i + 1}: ${t.slice(0, 80)}`);
      });
    }
  });

  it('the Node gate runs node:test under Node, never bun', () => {
    // More --import loaders may follow tsx, such as the active-handles report (A-223); the runner stays node --test.
    assert.match(PACKAGE.scripts['test:node'] ?? '', /^node --import tsx( --import \S+)* --test /);
    assert.doesNotMatch(PACKAGE.scripts['check:node'] ?? '', /\bbun\b/);
    assert.match(PACKAGE.scripts['check:node'] ?? '', /\btest:node\b/);
  });

  it('R17 a costs script runs cli/costs.ts and README.md documents it in one block', () => {
    assert.equal(PACKAGE.scripts.costs, 'bun src/cli/costs.ts');
    const readme = readmeDocs();
    const blocks = [...readme.matchAll(/```sh\n([\s\S]*?)```/g)].filter((b) => b[1]!.includes('bun run costs'));
    assert.equal(blocks.length, 1);
    assert.ok(!readme.includes('There is no `bun run costs`'));
  });
});

/** The docs an evaluator follows (YOS-201). Every command in them, fenced or inline, is checked. */
const EVALUATOR_DOCS = ['README.md', 'prod/README.md', 'prod/prompts/README.md', 'research/live-run-runbook.md', 'research/studio-demo-runbook.md'];

/**
 * One documented command: a package.json script (`bun run x`, `npm run x`), a repo script (`scripts/x.sh`, from the repo
 * root or code/), or a code/scripts entry (`bun scripts/x.ts`), with its arguments up to the next `&&`, `;`, `|` or `#`.
 */
type DocCommand = { readonly file: string; readonly line: number; readonly head: string; readonly args: readonly string[] };
const COMMAND = /(?<![\w./-])(bun run [a-z][\w:-]*|npm run [a-z][\w:-]*|(?:\.\.\/)?scripts\/[\w.-]+\.sh|bun (?:\.\.\/)?scripts\/[\w./-]+\.ts)([^`&;|#\n]*)/g;

/** Every command in `file`'s fenced blocks (with `\` continuations joined) and inline code spans, with its 1-based line. */
function docCommands(file: string): DocCommand[] {
  const out: DocCommand[] = [];
  const take = (text: string, line: number): void => {
    // A `$(…)` inside the arguments is another command's (`--commit $(git rev-parse --short HEAD)`), so it is dropped.
    for (const m of text.matchAll(COMMAND)) out.push({ file, line, head: m[1]!, args: m[2]!.replace(/\$\([^)]*\)/g, '').trim().split(/\s+/).filter((a) => a !== '') });
  };
  let fenced = false;
  let pending: { text: string; line: number } | null = null;
  readFileSync(path.join(REPO_DIR, file), 'utf8').split('\n').forEach((raw, i) => {
    if (raw.trimStart().startsWith('```')) {
      fenced = !fenced;
      return;
    }
    if (fenced) {
      const text = pending === null ? raw : `${pending.text} ${raw.trim()}`;
      const line = pending === null ? i + 1 : pending.line;
      if (text.trimEnd().endsWith('\\')) pending = { text: text.trimEnd().slice(0, -1), line };
      else {
        pending = null;
        take(text, line);
      }
      return;
    }
    for (const span of raw.matchAll(/`([^`]+)`/g)) take(span[1]!, i + 1);
  });
  return out;
}

/** The file a repo or code/scripts command runs, from the repo root. */
const scriptFileOf = (head: string): string => {
  const rel = head.replace(/^bun /, '');
  if (rel.endsWith('.sh')) return rel.replace(/^\.\.\//, '');
  return rel.startsWith('../') ? rel.slice(3) : `code/${rel}`;
};

describe('every command the evaluator docs give is checked (YOS-201)', () => {
  const commands = EVALUATOR_DOCS.flatMap(docCommands);
  const at = (c: DocCommand): string => `${c.file}:${c.line}: ${c.head} ${c.args.join(' ')}`.trim();
  type Help = { readonly what: string; readonly status: number | null; readonly out: string };
  const helps = new Map<string, Help>();
  /**
   * What `c` runs, asked for its --help once per distinct target: a package.json CLI (with worldplay's subcommand), a
   * repo script or a code/scripts entry. Null for a script that runs the suite or the build, whose existence is all.
   */
  const helpFor = (c: DocCommand): Help | null => {
    let what: string;
    let run: () => ReturnType<typeof spawnSync>;
    if (c.head.includes('scripts/')) {
      const file = scriptFileOf(c.head);
      what = file;
      run = () => (file.endsWith('.sh')
        ? spawnSync('bash', [file, '--help'], { cwd: REPO_DIR, encoding: 'utf8' })
        : spawnSync('node', ['--import', 'tsx', path.relative(CODE_DIR, path.join(REPO_DIR, file)), '--help'], { cwd: CODE_DIR, encoding: 'utf8' }));
    } else {
      const script = c.head.split(' ')[2]!;
      const m = NOT_CLI.has(script) ? null : /^(?:bun|tsx) (\S+\.ts)(?: (\w+))?$/.exec(PACKAGE.scripts[script] ?? '');
      if (m === null) return null;
      const [, entry, fixed] = m;
      const first = c.args[0] === '--' ? c.args[1] : c.args[0];
      const sub = fixed ?? (script === 'worldplay' && /^[a-z]+$/.test(first ?? '') ? first : undefined);
      what = `${entry} ${sub ?? ''}`.trim();
      run = () => spawnSync('node', ['--import', 'tsx', entry!, ...(sub === undefined ? [] : [sub]), '--help'], { cwd: CODE_DIR, encoding: 'utf8' });
    }
    if (!helps.has(what)) {
      const r = run();
      helps.set(what, { what, status: r.status, out: `${String(r.stdout)}${String(r.stderr)}` });
    }
    return helps.get(what)!;
  };
  const subs = [...helpOf('src/cli/worldplay.ts').stdout.matchAll(/^ {2}([a-z]+) /gm)].map((m) => m[1]);

  it('finds the documented commands in each file, fenced and inline', () => {
    const heads = (file: string): string[] => [...new Set(commands.filter((c) => c.file === file).map((c) => c.head))].sort();
    assert.deepEqual(heads('README.md'), ['bun run check', 'bun run live', 'bun run studio', 'bun run test', 'bun run worldgen', 'bun run worldplay', 'npm run check:node', 'scripts/demo-all.sh']);
    assert.deepEqual(heads('prod/README.md'), ['../scripts/live.sh', 'bun run docs', 'bun run live', 'bun run test', 'bun run worldgen', 'bun run worldplay']);
    assert.deepEqual(heads('prod/prompts/README.md'), ['bun run live', 'bun run worldgen']);
    assert.deepEqual(heads('research/live-run-runbook.md'), [
      'bun run check', 'bun run costs', 'bun run live', 'bun run test', 'bun run worldgen', 'bun run worldplay', 'npm run check:node',
      'scripts/boat-ci.sh', 'scripts/live.sh', 'scripts/solve-demo.sh',
    ]);
    assert.deepEqual(heads('research/studio-demo-runbook.md'), ['bun run studio', 'bun scripts/studio-rehearse.ts', 'scripts/studio-deploy.sh']);
  });

  it('names a package.json script for every `bun run` and `npm run`, and each CLI answers --help with 0', () => {
    for (const c of commands.filter((x) => !x.head.includes('scripts/'))) {
      const script = c.head.split(' ')[2]!;
      assert.ok(PACKAGE.scripts[script] !== undefined, `${at(c)}: package.json has no script "${script}"`);
      const h = helpFor(c);
      if (h !== null) assert.equal(h.status, 0, `${at(c)}: ${h.what} --help`);
    }
  });

  it('names a script that exists for every repo or code/scripts command, and each answers --help with 0', () => {
    for (const c of commands.filter((x) => x.head.includes('scripts/'))) {
      assert.ok(existsSync(path.join(REPO_DIR, scriptFileOf(c.head))), `${at(c)}: no ${scriptFileOf(c.head)}`);
      assert.equal(helpFor(c)?.status, 0, `${at(c)}: ${scriptFileOf(c.head)} --help`);
    }
  });

  it('gives worldplay only its subcommands, and every command only flags its --help names', () => {
    for (const c of commands) {
      if (c.head === 'bun run worldplay' && /^[a-z]+$/.test(c.args[0] ?? '')) assert.ok(subs.includes(c.args[0]), `${at(c)}: worldplay ${c.args[0]} is not a subcommand`);
      const h = helpFor(c);
      if (h === null) continue;
      for (const f of c.args.map((a) => a.replace(/=.*$/, '')).filter((a) => /^--[a-z][-a-z]*$/.test(a) && a !== '--help')) {
        assert.ok(new RegExp(`(^|[^\\w-])${f}(?![\\w-])`).test(h.out), `${at(c)}: ${h.what} --help names no ${f}`);
      }
    }
  });
});

describe('Docker', () => {
  const dockerfile = readFileSync(path.join(REPO_DIR, 'Dockerfile'), 'utf8');
  const run = shCommands(readmeDocs()).filter((c) => c.startsWith('docker '));
  const jsonArray = (instruction: string): string[] => {
    const m = new RegExp(`^${instruction} (\\[.*\\])$`, 'm').exec(dockerfile);
    assert.ok(m !== null, `Dockerfile has no ${instruction}`);
    return z.array(z.string()).parse(JSON.parse(m[1]!));
  };

  it('R18 Docker documents a private default and explicit host-loopback admin access', () => {
    assert.deepEqual(run, [
      'docker build -t worldplay .',
      'docker run -d --rm --name worldplay -p 4000:4000 worldplay serve /worlds/helpdesk --port 4000',
      'docker stop worldplay',
      'docker run -d --rm --name worldplay -p 4000:4000 -p 127.0.0.1:4001:4001 worldplay serve /worlds/helpdesk --port 4000 --admin-host 0.0.0.0',
    ]);
  });

  it('R18 the documented run command is the image name plus the ENTRYPOINT subcommand, and CMD serves the same world', () => {
    assert.deepEqual(jsonArray('ENTRYPOINT'), ['worldplay']);
    assert.deepEqual(jsonArray('CMD'), ['serve', '/worlds/helpdesk', '--port', '4000']);
    assert.ok(run[1]!.endsWith(` worldplay ${jsonArray('CMD').join(' ')}`));
  });

  it('R18 the Dockerfile exposes only the world port, copies the world, runs as node and keeps admin on loopback', () => {
    assert.ok(dockerfile.split('\n').includes('EXPOSE 4000'));
    assert.ok(dockerfile.split('\n').includes('COPY prod/worlds/ /worlds/'));
    assert.ok(dockerfile.split('\n').includes('USER node'));
    assert.ok(dockerfile.split('\n').includes('ENV WORLDPLAY_HOST=0.0.0.0'));
    assert.ok(dockerfile.split('\n').includes('ENV WORLDPLAY_ADMIN_HOST=127.0.0.1'));
    assert.ok(dockerfile.split('\n').includes('FROM node:22-slim'));
    assert.ok(existsSync(path.join(REPO_DIR, 'prod/worlds/helpdesk/world.yaml')));
  });

  it('R18 the image probes /openapi.json on the world port, and the README waits on that health status', () => {
    const health = dockerfile.replace(/\\\n\s*/g, ' ').split('\n').find((l) => l.startsWith('HEALTHCHECK '));
    assert.ok(health !== undefined, 'Dockerfile has no HEALTHCHECK');
    assert.ok(health.includes('http://127.0.0.1:4000/openapi.json'));
    const readme = readmeDocs();
    assert.ok(readme.includes("docker inspect -f '{{.State.Health.Status}}' worldplay)\" = healthy"));
  });

  it('R18 .dockerignore keeps secrets, history and run output out of the build context', () => {
    const ignored = readFileSync(path.join(REPO_DIR, '.dockerignore'), 'utf8').split('\n');
    for (const entry of ['.git', '**/node_modules', '.env', '.env.*', 'eval', '.claude']) assert.ok(ignored.includes(entry), entry);
  });
});

/** Cells in a markdown table row; `\|` is a literal pipe, not a separator. */
function cellCount(row: string): number {
  return row.trim().replace(/^\|/, '').replace(/(?<!\\)\|$/, '').split(/(?<!\\)\|/).length;
}

/** One message per malformed table in `markdown`: a table without header and separator, or a row whose cell count differs from its header. */
export function tableProblems(file: string, markdown: string): string[] {
  const lines = markdown.split('\n');
  const isRow = (l: string | undefined): boolean => l !== undefined && l.trimStart().startsWith('|');
  const problems: string[] = [];
  let i = 0;
  while (i < lines.length) {
    if (!isRow(lines[i])) {
      i++;
      continue;
    }
    const header = lines[i]!;
    const n = cellCount(header);
    const sep = lines[i + 1];
    const hasSep = sep !== undefined && /^\s*\|(\s*:?-+:?\s*\|)+\s*$/.test(sep);
    if (!hasSep) problems.push(`${file}:${i + 1}: table has no header and separator: ${header.slice(0, 60)}`);
    else if (cellCount(sep) !== n) problems.push(`${file}:${i + 2}: expected ${n} cells, found ${cellCount(sep)}: ${sep.slice(0, 60)}`);
    for (i += hasSep ? 2 : 1; isRow(lines[i]); i++) {
      const found = cellCount(lines[i]!);
      if (found !== n) problems.push(`${file}:${i + 1}: expected ${n} cells, found ${found}: ${lines[i]!.slice(0, 60)}`);
    }
  }
  return problems;
}

/**
 * Rows of research/decisions.md whose id is not `A-<n>`, in file order: the forms the log used before ids came from the
 * master (rule 14), and `-` for an early spec ambiguity with no id. A new row takes an `A-<n>` id; this list never grows.
 */
const LEGACY_DECISION_IDS: readonly string[] = [
  'U-BOAT-READINESS', 'U-BOAT-PROXY-BIND', 'U-BOAT-SONNET-DATASET', '-', '-', 'A-STAGE-TIME', 'A-WORKFLOW-EFFORT', '-', 'YOS-144',
  '-', '-', 'YOS-144 startup', 'A-BOAT-CREATE-IDENTITY', 'A-COST-2', 'A-COST-3', 'A-BOAT-UTC-USAGE', 'A-BOAT-KEY-PREFLIGHT',
  'A-OBSERVED-EXPOSURE', 'A-BOAT-RECEIPT-CAPTURE', 'A-VERIFIED-USAGE-RECONCILIATION', 'A-MODEL-PARTIAL-FINALITY',
  'A-TRANSPORT-STALL-COST', 'A-ITERATE-FS-SEAM', 'A-GEN-CANCEL', 'A-CANCELLATION-NATIVE-COMPOSITION', 'A-HTTP-REFUSED-COMMIT', 'YOS-149',
];
const DECISION_COLUMNS = ['Decision', 'Choice', 'Why', 'Date', 'Reversible'];
const cellsOf = (row: string): string[] => row.trim().replace(/^\|/, '').replace(/(?<!\\)\|$/, '').split(/(?<!\\)\|/).map((c) => c.trim());

/**
 * One message per row of a decision log that breaks its structure (YOS-201): a header that does not name the five
 * columns, an id that is neither `A-<n>` nor on the `legacy` list in its place, an `A-<n>` used twice (`A-07` is `A-7`),
 * an empty decision, choice or why, a date that is not YYYY-MM-DD, or a reversible cell that does not start with yes or no.
 * Rows stay in append order, so nothing here asks for numeric order.
 */
export function decisionProblems(file: string, markdown: string, legacy: readonly string[]): string[] {
  const lines = markdown.split('\n');
  const problems: string[] = [];
  const first = new Map<string, number>();
  const others: string[] = [];
  const isSep = (l: string | undefined): boolean => l !== undefined && /^\s*\|(\s*:?-+:?\s*\|)+\s*$/.test(l);
  lines.forEach((line, i) => {
    if (!line.trimStart().startsWith('|') || isSep(line)) return;
    const at = `${file}:${i + 1}`;
    const cells = cellsOf(line);
    if (isSep(lines[i + 1])) {
      const named = cells.slice(1).map((c) => c.replace(/\?$/, ''));
      if (JSON.stringify(named) !== JSON.stringify(DECISION_COLUMNS)) problems.push(`${at}: the header names ${named.join(', ')}, not ${DECISION_COLUMNS.join(', ')}`);
      return;
    }
    const [id = '', decision = '', choice = '', why = '', date = '', reversible = ''] = cells;
    const n = /^A-(\d+)$/.exec(id);
    if (n === null) others.push(id);
    else {
      const key = `A-${Number(n[1])}`;
      const seen = first.get(key);
      if (seen !== undefined) problems.push(`${at}: ${id} is used again; line ${seen} has it`);
      else first.set(key, i + 1);
    }
    if (cells.length !== 6) problems.push(`${at}: ${id} has ${cells.length - 1} columns, not the five ${DECISION_COLUMNS.join(', ')}`);
    for (const [name, text] of [['decision', decision], ['choice', choice], ['why', why]] as const) if (text === '') problems.push(`${at}: ${id} has no ${name}`);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) problems.push(`${at}: ${id} has date "${date}", not YYYY-MM-DD`);
    if (!/^(yes|no)\b/i.test(reversible)) problems.push(`${at}: ${id} has reversible "${reversible}", which starts with neither yes nor no`);
  });
  if (JSON.stringify(others) !== JSON.stringify(legacy)) problems.push(`${file}: ids not of the form A-<n> are ${JSON.stringify(others)}, not the legacy list ${JSON.stringify(legacy)}`);
  return problems;
}

describe('research/decisions.md tables', () => {
  it('a table needs a header and separator, and every row its header\'s cell count; `\\|` is not a separator', () => {
    const md = [
      '| ID | Decision | Reversible |',
      '|---|---|---|',
      '| A-1 | `a \\| b` | Yes |',
      '| A-2 | one | two | Yes |',
      '',
      '| A-3 | orphan | Yes |',
    ].join('\n');
    assert.deepEqual(tableProblems('d.md', md), [
      'd.md:4: expected 3 cells, found 4: | A-2 | one | two | Yes |',
      'd.md:6: table has no header and separator: | A-3 | orphan | Yes |',
    ]);
  });

  it('every table in research/decisions.md is well-formed', () => {
    const file = 'research/decisions.md';
    assert.deepEqual(tableProblems(file, readFileSync(path.join(REPO_DIR, file), 'utf8')), []);
  });

  it('a decision row needs a unique A-<n> id or a legacy one in its place, five columns, a date and a yes or no (YOS-201)', () => {
    const md = [
      '| # | Decision | Choice | Why | Date | Reversible? |',
      '|---|---|---|---|---|---|',
      '| A-1 | one | c | w | 2026-10-08 | Yes |',
      '| A-01 | the same id, padded | c | w | 2026-10-08 | yes |',
      '| B-7 | not an A id | c | w | 2026-10-08 | No |',
      '| - | Spec: no id | c | w | 2026-10-08 | Yes, by a new row |',
      '| A-2 | a column short, its choice empty |  | 2026-10-08 | Yes |',
      '| A-3 | bad date and reversible | c | w | 8 Oct | - |',
      '',
      '| ID | Decision | Choice | Rationale | Date | Reversible |',
      '| --- | --- | --- | --- | --- | --- |',
      '| A-4 | four | c | w | 2026-10-08 | No |',
    ].join('\n');
    assert.deepEqual(decisionProblems('d.md', md, ['-']), [
      'd.md:4: A-01 is used again; line 3 has it',
      'd.md:7: A-2 has 4 columns, not the five Decision, Choice, Why, Date, Reversible',
      'd.md:7: A-2 has no choice',
      'd.md:7: A-2 has date "Yes", not YYYY-MM-DD',
      'd.md:7: A-2 has reversible "", which starts with neither yes nor no',
      'd.md:8: A-3 has date "8 Oct", not YYYY-MM-DD',
      'd.md:8: A-3 has reversible "-", which starts with neither yes nor no',
      'd.md:10: the header names Decision, Choice, Rationale, Date, Reversible, not Decision, Choice, Why, Date, Reversible',
      'd.md: ids not of the form A-<n> are ["B-7","-"], not the legacy list ["-"]',
    ]);
  });

  it('every row of research/decisions.md has a unique A-<n> id or its legacy one, five columns, a date and a yes or no', () => {
    const file = 'research/decisions.md';
    assert.deepEqual(decisionProblems(file, readFileSync(path.join(REPO_DIR, file), 'utf8'), LEGACY_DECISION_IDS), []);
  });
});
